# -*- coding: UTF-8 -*-

import prints
def printShoppingQueue(printer):
	prints.printHead(printer);
	prints.putLine("Obst & Gemüse", printer);
	prints.printItem(printer);
	prints.putLine("Eisbergsalat x1", printer);
	prints.putLine("Paprika x1", printer);
	prints.putLine("Bananen x1", printer);
	prints.putLine("Gurken x1", printer);
	prints.putLine("Blumenkohl x1", printer);
	prints.putLine("Zuccini x3", printer);
	prints.printHead(printer);
	prints.putLine("Kochen & Backen", printer);
	prints.printItem(printer);
	prints.putLine("Nudeln x1", printer);
	prints.putLine("Vitalis Honig-Mandel x1", printer);
	prints.printHead(printer);
	prints.putLine("Konserven", printer);
	prints.printItem(printer);
	prints.putLine("Apfelmus x1", printer);
	prints.printHead(printer);
	prints.putLine("Drogerie", printer);
	prints.printItem(printer);
	prints.putLine("Toilettenpapier x1", printer);
	prints.putLine("Geschirrspüler x1", printer);
	prints.putLine("WC Reiniger (Ente) x1", printer);
	prints.printHead(printer);
	prints.putLine("Backwaren", printer);
	prints.printItem(printer);
	prints.putLine("Aufback Brötchen x1", printer);
	prints.printHead(printer);
	prints.putLine("Molkerei/Eier/Butter", printer);
	prints.printItem(printer);
	prints.putLine("Eier x2", printer);
	prints.putLine("Eiersalat x2", printer);
	prints.putLine("Butter x2", printer);
	prints.putLine("Milch x3", printer);
	prints.putLine("Pudding x4", printer);
	prints.putLine("Käse, gestiftet x1", printer);
	prints.printHead(printer);
	prints.putLine("Nährmittel", printer);
	prints.printItem(printer);
	prints.putLine("Pfeffersoße x1", printer);
	prints.putLine("Suppentopf x2", printer);
	prints.printHead(printer);
	prints.putLine("Tiefkühlkost", printer);
	prints.printItem(printer);
	prints.putLine("TK Gemüse x1", printer);
	prints.putLine("Semmelknödel x1", printer);
	prints.putLine("Bohnen x1", printer);
	prints.printHead(printer);
	prints.putLine("SB Fleisch & Wurst", printer);
	prints.printItem(printer);
	prints.putLine("Hackfleisch 500g x1", printer);
	prints.putLine("Fleischwurst x1", printer);
	prints.putLine("Leberkäse x2", printer);
	prints.putLine("Hühnchen x1", printer);
	prints.putLine("Schweinelende x1", printer);
	prints.printHead(printer);
	prints.putLine("Getränke", printer);
	prints.printItem(printer);
	prints.putLine("Cola x1", printer);
